// Autogenerated from Pigeon (v16.0.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FlutterMediationExtrasHandler.
NSObject<FlutterMessageCodec> *FlutterMediationExtrasHandlerGetCodec(void);

@protocol FlutterMediationExtrasHandler
/// @return `nil` only when `error != nil`.
- (nullable id)generateExtrasExtras:(nullable NSDictionary<NSString *, id> *)extras error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFlutterMediationExtrasHandler(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterMediationExtrasHandler> *_Nullable api);

NS_ASSUME_NONNULL_END
