name: rewarded_interstitial_example
description: Example project for demoing rewarded interstitial ads.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter/
      path: ./packages/google_mobile_ads

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
