name: gma_mediation_unity
description: "Mediation Adapter for Unity Ads to use with Google Mobile Ads."
version: 1.0.0
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/mediation

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_unity
        pluginClass: GmaMediationUnityPlugin
      ios:
        pluginClass: GmaMediationUnityPlugin
