// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class IronSourcePrivacyApiPigeonCodecReader: FlutterStandardReader {
}

private class IronSourcePrivacyApiPigeonCodecWriter: FlutterStandardWriter {
}

private class IronSourcePrivacyApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IronSourcePrivacyApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IronSourcePrivacyApiPigeonCodecWriter(data: data)
  }
}

class IronSourcePrivacyApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IronSourcePrivacyApiPigeonCodec(
    readerWriter: IronSourcePrivacyApiPigeonCodecReaderWriter())
}

/// The generated classes set the channels to call the methods in the corresponding kotlin IronSourcePrivacyApi interface and swift IronSourcePrivacyApi protocol from the dart layer.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IronSourcePrivacyApi {
  func setConsent(gdprConsent: Bool) throws
  func setDoNotSell(doNotSell: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IronSourcePrivacyApiSetup {
  static var codec: FlutterStandardMessageCodec { IronSourcePrivacyApiPigeonCodec.shared }
  /// Sets up an instance of `IronSourcePrivacyApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: IronSourcePrivacyApi?,
    messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setConsentChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.gma_mediation_ironsource.IronSourcePrivacyApi.setConsent\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let gdprConsentArg = args[0] as! Bool
        do {
          try api.setConsent(gdprConsent: gdprConsentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setConsentChannel.setMessageHandler(nil)
    }
    let setDoNotSellChannel = FlutterBasicMessageChannel(
      name:
        "dev.flutter.pigeon.gma_mediation_ironsource.IronSourcePrivacyApi.setDoNotSell\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDoNotSellChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let doNotSellArg = args[0] as! Bool
        do {
          try api.setDoNotSell(doNotSell: doNotSellArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDoNotSellChannel.setMessageHandler(nil)
    }
  }
}
