// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.googlemobileads.mediation.gma_mediation_chartboost

import android.util.Log
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private object ChartboostSDKApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(exception.code, exception.message, exception.details)
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : RuntimeException()

private open class ChartboostSDKApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return super.readValueOfType(type, buffer)
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    super.writeValue(stream, value)
  }
}

/**
 * The generated classes set the channels to call the methods in the corresponding kotlin
 * ChartboostSDKApi interface and swift ChartboostSDKApi protocol from the dart layer.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface ChartboostSDKApi {

  companion object {
    /** The codec used by ChartboostSDKApi. */
    val codec: MessageCodec<Any?> by lazy { ChartboostSDKApiPigeonCodec() }

    /**
     * Sets up an instance of `ChartboostSDKApi` to handle messages through the `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: ChartboostSDKApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    }
  }
}
