name: gma_mediation_meta
description: "Mediation Adapter for Meta Audience Network to use with Google Mobile Ads."
version: 1.0.0
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/mediation

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_meta
        pluginClass: GmaMediationMetaPlugin
      ios:
        pluginClass: GmaMediationMetaPlugin
