blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/googleads/googleads-mobile-flutter/discussions/categories/ideas
    about: Share ideas for new features.
  - name: Ask a Question
    url: https://github.com/googleads/googleads-mobile-flutter/discussions/categories/q-a
    about: Ask the community for help.
  - name: Show and tell
    url: https://github.com/googleads/googleads-mobile-flutter/discussions/categories/show-and-tell
    about: Share what you've built with the Google Mobile Ads Flutter plugin.
