blank_issues_enabled: true
contact_links:
  - name: I want help writing my application
    url: https://stackoverflow.com/tags/flutter
    about: Ask your questions about how to achieve a particular effect in Flutter or get help with using a particular API.
  - name: I have a problem with the Google Mobile Ads SDK.
    url: https://support.google.com/admob/gethelp
    about: I need help with an issue with Google Mobile Ads that doesn't relate specifically to this plugin or Flutter.
  - name: I have a problem with the Google AdManager.
    url: https://support.google.com/admanager/answer/3059042#contact=1
    about: I need help with an issue with Google AdManager that doesn't relate specifically to this plugin or Flutter.
