blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/googleads/googleads-mobile-flutter/discussions/new?category_id=24213383
    about: Share ideas for new features.
  - name: Ask a Question
    url: https://github.com/googleads/googleads-mobile-flutter/discussions/new?category_id=24213382
    about: Ask the community for help.
  - name: Show and tell
    url: https://github.com/googleads/googleads-mobile-flutter/new?category_id=24213384
    about: Share what you've built with the Google Mobile Ads Flutter plugin.
