// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.googlemobileads.mediation.gma_mediation_applovin

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(exception.code, exception.message, exception.details)
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : Throwable()

private open class AppLovinSDKApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return super.readValueOfType(type, buffer)
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    super.writeValue(stream, value)
  }
}

/**
 * The generated classes set the channels to call the methods in the corresponding kotlin
 * AppLovinSDKApi interface and swift AppLovinSDKApi protocol from the dart layer.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AppLovinSDKApi {
  /** Used to configure GDPR consent on the Android or iOS AppLovin SDK */
  fun setHasUserConsent(hasUserConsent: Boolean)

  /** Used to opt out of the sale of personal information in AppLovin SDK. */
  fun setDoNotSell(doNotSell: Boolean)

  companion object {
    /** The codec used by AppLovinSDKApi. */
    val codec: MessageCodec<Any?> by lazy { AppLovinSDKApiPigeonCodec() }

    /** Sets up an instance of `AppLovinSDKApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: AppLovinSDKApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.gma_mediation_applovin.AppLovinSDKApi.setHasUserConsent$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hasUserConsentArg = args[0] as Boolean
            val wrapped: List<Any?> =
              try {
                api.setHasUserConsent(hasUserConsentArg)
                listOf(null)
              } catch (exception: Throwable) {
                wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.gma_mediation_applovin.AppLovinSDKApi.setDoNotSell$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val doNotSellArg = args[0] as Boolean
            val wrapped: List<Any?> =
              try {
                api.setDoNotSell(doNotSellArg)
                listOf(null)
              } catch (exception: Throwable) {
                wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
