// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// The generated classes set the channels to call the methods in the corresponding kotlin InMobiPrivacyApi interface and swift InMobiPrivacyApi protocol from the dart layer.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol InMobiPrivacyApi {
  /// Used to configure GDPR on the Android or iOS InMobi SDK
  func updateGDPRConsent(isGDPRApplicable: Bool, gdprConsent: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class InMobiPrivacyApiSetup {
  /// The codec used by InMobiPrivacyApi.
  /// Sets up an instance of `InMobiPrivacyApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: InMobiPrivacyApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Used to configure GDPR on the Android or iOS InMobi SDK
    let updateGDPRConsentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gma_mediation_inmobi.InMobiPrivacyApi.updateGDPRConsent\(channelSuffix)", binaryMessenger: binaryMessenger)
    if let api = api {
      updateGDPRConsentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isGDPRApplicableArg = args[0] as! Bool
        let gdprConsentArg = args[1] as! Bool
        do {
          try api.updateGDPRConsent(isGDPRApplicable: isGDPRApplicableArg, gdprConsent: gdprConsentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateGDPRConsentChannel.setMessageHandler(nil)
    }
  }
}
