name: gma_mediation_liftoffmonetize
description: "Mediation Adapter for Liftoff Monetize to use with Google Mobile Ads."
version: 1.0.0
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/mediation
publish_to: none

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads:
    path: ../../
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^17.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_liftoffmonetize
        pluginClass: GmaMediationLiftoffmonetizePlugin
      ios:
        pluginClass: GmaMediationLiftoffmonetizePlugin
