name: gma_mediation_moloco
description: 'Mediation Adapter that enables sending ad requests to the Moloco
  ad network using the google_mobile_ads plugin.'
version: 3.4.0
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^8.0.0
  meta: ^1.17.0
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lint: ^2.4.0
  pigeon: ^26.3.4
flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_moloco
        pluginClass: GmaMediationMolocoPlugin
      ios:
        pluginClass: GmaMediationMolocoPlugin
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_moloco
