// Autogenerated from Pigeon (v17.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiftoffPrivacyApi {
  func setGDPRStatus(optedIn: Bool, consentMessageVersion: String?) throws
  func setCCPAStatus(optedIn: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiftoffPrivacyApiSetup {
  /// The codec used by LiftoffPrivacyApi.
  /// Sets up an instance of `LiftoffPrivacyApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiftoffPrivacyApi?) {
    let setGDPRStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gma_mediation_liftoffmonetize.LiftoffPrivacyApi.setGDPRStatus", binaryMessenger: binaryMessenger)
    if let api = api {
      setGDPRStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optedInArg = args[0] as! Bool
        let consentMessageVersionArg: String? = nilOrValue(args[1])
        do {
          try api.setGDPRStatus(optedIn: optedInArg, consentMessageVersion: consentMessageVersionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setGDPRStatusChannel.setMessageHandler(nil)
    }
    let setCCPAStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.gma_mediation_liftoffmonetize.LiftoffPrivacyApi.setCCPAStatus", binaryMessenger: binaryMessenger)
    if let api = api {
      setCCPAStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optedInArg = args[0] as! Bool
        do {
          try api.setCCPAStatus(optedIn: optedInArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCCPAStatusChannel.setMessageHandler(nil)
    }
  }
}
