// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.googlemobileads.mediation.gma_mediation_liftoffmonetize

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private object LiftoffPrivacyApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(exception.code, exception.message, exception.details)
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 *
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
  val code: String,
  override val message: String? = null,
  val details: Any? = null,
) : RuntimeException()

private open class LiftoffPrivacyApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return super.readValueOfType(type, buffer)
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    super.writeValue(stream, value)
  }
}

/**
 * The generated classes set the channels to call the methods in the corresponding kotlin
 * LiftoffPrivacyApi interface and swift LiftoffPrivacyApi protocol from the dart layer.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LiftoffPrivacyApi {
  /** Used to configure GDPR status on the Android or iOS Liftoff Monetize SDK */
  fun setGDPRStatus(optedIn: Boolean, consentMessageVersion: String?)

  /** Used to configure CCPA consent on the Android or iOS Liftoff Monetize SDK */
  fun setCCPAStatus(optedIn: Boolean)

  companion object {
    /** The codec used by LiftoffPrivacyApi. */
    val codec: MessageCodec<Any?> by lazy { LiftoffPrivacyApiPigeonCodec() }

    /**
     * Sets up an instance of `LiftoffPrivacyApi` to handle messages through the `binaryMessenger`.
     */
    @JvmOverloads
    fun setUp(
      binaryMessenger: BinaryMessenger,
      api: LiftoffPrivacyApi?,
      messageChannelSuffix: String = "",
    ) {
      val separatedMessageChannelSuffix =
        if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.gma_mediation_liftoffmonetize.LiftoffPrivacyApi.setGDPRStatus$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optedInArg = args[0] as Boolean
            val consentMessageVersionArg = args[1] as String?
            val wrapped: List<Any?> =
              try {
                api.setGDPRStatus(optedInArg, consentMessageVersionArg)
                listOf(null)
              } catch (exception: Throwable) {
                LiftoffPrivacyApiPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel =
          BasicMessageChannel<Any?>(
            binaryMessenger,
            "dev.flutter.pigeon.gma_mediation_liftoffmonetize.LiftoffPrivacyApi.setCCPAStatus$separatedMessageChannelSuffix",
            codec,
          )
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optedInArg = args[0] as Boolean
            val wrapped: List<Any?> =
              try {
                api.setCCPAStatus(optedInArg)
                listOf(null)
              } catch (exception: Throwable) {
                LiftoffPrivacyApiPigeonUtils.wrapError(exception)
              }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
