name: gma_mediation_pangle
description: "Mediation Adapter for Pangle to use with Google Mobile Ads."
version: 1.0.0
repository: https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/mediation/gma_mediation_pangle

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.googlemobileads.mediation.gma_mediation_pangle
        pluginClass: GmaMediationPanglePlugin
      ios:
        pluginClass: GmaMediationPanglePlugin
