// Mocks generated by Mockito 5.3.2 from annotations
// in google_mobile_ads/example/ios/.symlinks/plugins/google_mobile_ads/test/mobile_ads_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i3;

import 'package:flutter/services.dart' as _i4;
import 'package:google_mobile_ads/src/ad_containers.dart' as _i7;
import 'package:google_mobile_ads/src/ad_inspector_containers.dart' as _i14;
import 'package:google_mobile_ads/src/ad_instance_manager.dart' as _i13;
import 'package:google_mobile_ads/src/mobile_ads.dart' as _i6;
import 'package:google_mobile_ads/src/request_configuration.dart' as _i8;
import 'package:google_mobile_ads/src/webview_controller_util.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:webview_flutter/src/navigation_delegate.dart' as _i12;
import 'package:webview_flutter/webview_flutter.dart' as _i9;
import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlatformWebViewController_0 extends _i1.SmartFake
    implements _i2.PlatformWebViewController {
  _FakePlatformWebViewController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_1 extends _i1.SmartFake implements Object {
  _FakeObject_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOffset_2 extends _i1.SmartFake implements _i3.Offset {
  _FakeOffset_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMethodChannel_3 extends _i1.SmartFake implements _i4.MethodChannel {
  _FakeMethodChannel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebViewControllerUtil_4 extends _i1.SmartFake
    implements _i5.WebViewControllerUtil {
  _FakeWebViewControllerUtil_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInitializationStatus_5 extends _i1.SmartFake
    implements _i6.InitializationStatus {
  _FakeInitializationStatus_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdSize_6 extends _i1.SmartFake implements _i7.AdSize {
  _FakeAdSize_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestConfiguration_7 extends _i1.SmartFake
    implements _i8.RequestConfiguration {
  _FakeRequestConfiguration_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WebViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebViewController extends _i1.Mock implements _i9.WebViewController {
  MockWebViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlatformWebViewController get platform => (super.noSuchMethod(
        Invocation.getter(#platform),
        returnValue: _FakePlatformWebViewController_0(
          this,
          Invocation.getter(#platform),
        ),
      ) as _i2.PlatformWebViewController);
  @override
  _i10.Future<void> loadFile(String? absoluteFilePath) => (super.noSuchMethod(
        Invocation.method(
          #loadFile,
          [absoluteFilePath],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadFlutterAsset(String? key) => (super.noSuchMethod(
        Invocation.method(
          #loadFlutterAsset,
          [key],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadHtmlString(
    String? html, {
    String? baseUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadHtmlString,
          [html],
          {#baseUrl: baseUrl},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadRequest(
    Uri? uri, {
    _i2.LoadRequestMethod? method = _i2.LoadRequestMethod.get,
    Map<String, String>? headers = const {},
    _i11.Uint8List? body,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRequest,
          [uri],
          {
            #method: method,
            #headers: headers,
            #body: body,
          },
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String?> currentUrl() => (super.noSuchMethod(
        Invocation.method(
          #currentUrl,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<bool> canGoBack() => (super.noSuchMethod(
        Invocation.method(
          #canGoBack,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<bool> canGoForward() => (super.noSuchMethod(
        Invocation.method(
          #canGoForward,
          [],
        ),
        returnValue: _i10.Future<bool>.value(false),
      ) as _i10.Future<bool>);
  @override
  _i10.Future<void> goBack() => (super.noSuchMethod(
        Invocation.method(
          #goBack,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> goForward() => (super.noSuchMethod(
        Invocation.method(
          #goForward,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setNavigationDelegate(_i12.NavigationDelegate? delegate) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNavigationDelegate,
          [delegate],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> clearLocalStorage() => (super.noSuchMethod(
        Invocation.method(
          #clearLocalStorage,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> runJavaScript(String? javaScript) => (super.noSuchMethod(
        Invocation.method(
          #runJavaScript,
          [javaScript],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<Object> runJavaScriptReturningResult(String? javaScript) =>
      (super.noSuchMethod(
        Invocation.method(
          #runJavaScriptReturningResult,
          [javaScript],
        ),
        returnValue: _i10.Future<Object>.value(_FakeObject_1(
          this,
          Invocation.method(
            #runJavaScriptReturningResult,
            [javaScript],
          ),
        )),
      ) as _i10.Future<Object>);
  @override
  _i10.Future<void> addJavaScriptChannel(
    String? name, {
    required void Function(_i2.JavaScriptMessage)? onMessageReceived,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addJavaScriptChannel,
          [name],
          {#onMessageReceived: onMessageReceived},
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> removeJavaScriptChannel(String? javaScriptChannelName) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeJavaScriptChannel,
          [javaScriptChannelName],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String?> getTitle() => (super.noSuchMethod(
        Invocation.method(
          #getTitle,
          [],
        ),
        returnValue: _i10.Future<String?>.value(),
      ) as _i10.Future<String?>);
  @override
  _i10.Future<void> scrollTo(
    int? x,
    int? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrollTo,
          [
            x,
            y,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> scrollBy(
    int? x,
    int? y,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scrollBy,
          [
            x,
            y,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<_i3.Offset> getScrollPosition() => (super.noSuchMethod(
        Invocation.method(
          #getScrollPosition,
          [],
        ),
        returnValue: _i10.Future<_i3.Offset>.value(_FakeOffset_2(
          this,
          Invocation.method(
            #getScrollPosition,
            [],
          ),
        )),
      ) as _i10.Future<_i3.Offset>);
  @override
  _i10.Future<void> enableZoom(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #enableZoom,
          [enabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setBackgroundColor(_i3.Color? color) => (super.noSuchMethod(
        Invocation.method(
          #setBackgroundColor,
          [color],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setJavaScriptMode(_i2.JavaScriptMode? javaScriptMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setJavaScriptMode,
          [javaScriptMode],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setUserAgent(String? userAgent) => (super.noSuchMethod(
        Invocation.method(
          #setUserAgent,
          [userAgent],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [AdInstanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdInstanceManager extends _i1.Mock implements _i13.AdInstanceManager {
  MockAdInstanceManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MethodChannel get channel => (super.noSuchMethod(
        Invocation.getter(#channel),
        returnValue: _FakeMethodChannel_3(
          this,
          Invocation.getter(#channel),
        ),
      ) as _i4.MethodChannel);
  @override
  _i5.WebViewControllerUtil get webViewControllerUtil => (super.noSuchMethod(
        Invocation.getter(#webViewControllerUtil),
        returnValue: _FakeWebViewControllerUtil_4(
          this,
          Invocation.getter(#webViewControllerUtil),
        ),
      ) as _i5.WebViewControllerUtil);
  @override
  _i10.Future<_i6.InitializationStatus> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i10.Future<_i6.InitializationStatus>.value(
            _FakeInitializationStatus_5(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i10.Future<_i6.InitializationStatus>);
  @override
  _i10.Future<_i7.AdSize> getAdSize(_i7.Ad? ad) => (super.noSuchMethod(
        Invocation.method(
          #getAdSize,
          [ad],
        ),
        returnValue: _i10.Future<_i7.AdSize>.value(_FakeAdSize_6(
          this,
          Invocation.method(
            #getAdSize,
            [ad],
          ),
        )),
      ) as _i10.Future<_i7.AdSize>);
  @override
  _i7.Ad? adFor(int? adId) => (super.noSuchMethod(Invocation.method(
        #adFor,
        [adId],
      )) as _i7.Ad?);
  @override
  int? adIdFor(_i7.Ad? ad) => (super.noSuchMethod(Invocation.method(
        #adIdFor,
        [ad],
      )) as int?);
  @override
  bool isWidgetAdIdMounted(int? adId) => (super.noSuchMethod(
        Invocation.method(
          #isWidgetAdIdMounted,
          [adId],
        ),
        returnValue: false,
      ) as bool);
  @override
  void mountWidgetAdId(int? adId) => super.noSuchMethod(
        Invocation.method(
          #mountWidgetAdId,
          [adId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void unmountWidgetAdId(int? adId) => super.noSuchMethod(
        Invocation.method(
          #unmountWidgetAdId,
          [adId],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i10.Future<void> loadBannerAd(_i7.BannerAd? ad) => (super.noSuchMethod(
        Invocation.method(
          #loadBannerAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadInterstitialAd(_i7.InterstitialAd? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadInterstitialAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadNativeAd(_i7.NativeAd? ad) => (super.noSuchMethod(
        Invocation.method(
          #loadNativeAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadRewardedAd(_i7.RewardedAd? ad) => (super.noSuchMethod(
        Invocation.method(
          #loadRewardedAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadRewardedInterstitialAd(
          _i7.RewardedInterstitialAd? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadRewardedInterstitialAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadAppOpenAd(_i7.AppOpenAd? ad) => (super.noSuchMethod(
        Invocation.method(
          #loadAppOpenAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadAdManagerBannerAd(_i7.AdManagerBannerAd? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAdManagerBannerAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadFluidAd(_i7.FluidAdManagerBannerAd? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFluidAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> loadAdManagerInterstitialAd(
          _i7.AdManagerInterstitialAd? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAdManagerInterstitialAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> disposeAd(_i7.Ad? ad) => (super.noSuchMethod(
        Invocation.method(
          #disposeAd,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> showAdWithoutView(_i7.AdWithoutView? ad) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAdWithoutView,
          [ad],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<_i8.RequestConfiguration> getRequestConfiguration() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequestConfiguration,
          [],
        ),
        returnValue: _i10.Future<_i8.RequestConfiguration>.value(
            _FakeRequestConfiguration_7(
          this,
          Invocation.method(
            #getRequestConfiguration,
            [],
          ),
        )),
      ) as _i10.Future<_i8.RequestConfiguration>);
  @override
  _i10.Future<void> updateRequestConfiguration(
          _i8.RequestConfiguration? requestConfiguration) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRequestConfiguration,
          [requestConfiguration],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setSameAppKeyEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSameAppKeyEnabled,
          [isEnabled],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setAppMuted(bool? muted) => (super.noSuchMethod(
        Invocation.method(
          #setAppMuted,
          [muted],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setAppVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setAppVolume,
          [volume],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> setImmersiveMode(
    _i7.AdWithoutView? ad,
    bool? immersiveModeEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setImmersiveMode,
          [
            ad,
            immersiveModeEnabled,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> disableSDKCrashReporting() => (super.noSuchMethod(
        Invocation.method(
          #disableSDKCrashReporting,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> disableMediationInitialization() => (super.noSuchMethod(
        Invocation.method(
          #disableMediationInitialization,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<String> getVersionString() => (super.noSuchMethod(
        Invocation.method(
          #getVersionString,
          [],
        ),
        returnValue: _i10.Future<String>.value(''),
      ) as _i10.Future<String>);
  @override
  _i10.Future<void> setServerSideVerificationOptions(
    _i7.ServerSideVerificationOptions? options,
    _i7.Ad? ad,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setServerSideVerificationOptions,
          [
            options,
            ad,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> openDebugMenu(String? adUnitId) => (super.noSuchMethod(
        Invocation.method(
          #openDebugMenu,
          [adUnitId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  _i10.Future<void> registerWebView(_i9.WebViewController? controller) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWebView,
          [controller],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
  @override
  int getWebViewId(_i9.WebViewController? controller) => (super.noSuchMethod(
        Invocation.method(
          #getWebViewId,
          [controller],
        ),
        returnValue: 0,
      ) as int);
  @override
  void openAdInspector(_i14.OnAdInspectorClosedListener? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #openAdInspector,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WebViewControllerUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebViewControllerUtil extends _i1.Mock
    implements _i5.WebViewControllerUtil {
  MockWebViewControllerUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int webViewIdentifier(_i9.WebViewController? controller) =>
      (super.noSuchMethod(
        Invocation.method(
          #webViewIdentifier,
          [controller],
        ),
        returnValue: 0,
      ) as int);
}
