name: Build Status

permissions:
  contents: read

# Step 1: Build on pull-requests or pushes to main
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/google_mobile_ads/**"
      - "samples/admob/**"
      - ".github/workflows/build.yaml"
  push:
    branches:
      - main
    paths:
      - "packages/google_mobile_ads/**"
      - "samples/admob/**"
      - ".github/workflows/build.yaml"
 
jobs:
# Step 2: Build Android
  android:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        regex:
        - "samples/admob/api_demo"
        - "samples/admob/mediation_example"   
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable     
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }}     
      - name: "Build Android Example"
        run: ./.github/workflows/scripts/build-example.sh android ./lib/main.dart $GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }}   

# Step 2: Build iOS
  iOS:
    runs-on: macOS-latest
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        regex:
        - "samples/admob/api_demo"
        - "samples/admob/mediation_example" 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_26.2.app/Contents/Developer'  
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }}
      - name: "Build iOS Example"
        run: ./.github/workflows/scripts/build-example.sh ios ./lib/main.dart $GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }}   
          
# Step 3: Build Flutter
  flutter:
    name: Build Flutter
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        regex:
        - "samples/admob/api_demo"
        - "samples/admob/mediation_example" 
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }}        
      - name: "Flutter Analyze"
        run: |
          cd $GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE
          flutter clean
          flutter pub get
          flutter analyze
        env:
          GOOGLEMOBILEADS_PLUGIN_SCOPE_EXAMPLE: ${{ matrix.regex }} 
      - name: "Flutter Format"
        run: |
          dart format --version
          dart format samples/ --language-version latest
          ./.github/workflows/scripts/validate-formatting.sh
